// apps/next-app/app/[lang]/admin/subscriptions/columns.tsx
"use client"

import { ColumnDef } from "@tanstack/react-table"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { MoreHorizontal, ArrowUpDown, Copy, ExternalLink, RefreshCw, ArrowUp, ArrowDown } from "lucide-react"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu"
import { useTranslation } from "@/hooks/use-translation"

export type Subscription = {
  id: string
  userId: string | null
  planId: string | null
  status: string
  paymentType: string
  stripeCustomerId?: string | null
  stripeSubscriptionId?: string | null
  creemCustomerId?: string | null
  creemSubscriptionId?: string | null
  periodStart: string | Date | null
  periodEnd: string | Date | null
  cancelAtPeriodEnd?: boolean | null
  metadata?: any
  createdAt: string | Date | null
  updatedAt?: string | Date | null
  // 关联的用户信息
  userName?: string | null
  userEmail?: string | null
}

const getStatusBadge = (status: string, t: any) => {
  const statusConfig = {
    active: { label: t.admin.subscriptions.table.search.active, variant: "default" as const },
    canceled: { label: t.admin.subscriptions.table.search.canceled, variant: "secondary" as const },
    past_due: { label: t.admin.subscriptions.table.search.pastDue, variant: "destructive" as const },
    unpaid: { label: t.admin.subscriptions.table.search.unpaid, variant: "destructive" as const },
    trialing: { label: t.admin.subscriptions.table.search.trialing, variant: "outline" as const },
  }
  
  const config = statusConfig[status as keyof typeof statusConfig] || { label: status, variant: "outline" as const }
  return <Badge variant={config.variant}>{config.label}</Badge>
}

const getPaymentTypeBadge = (paymentType: string, t: any) => {
  const typeConfig = {
    one_time: { label: t.admin.subscriptions.table.search.oneTime, variant: "outline" as const },
    recurring: { label: t.admin.subscriptions.table.search.recurring, variant: "outline" as const },
  }
  
  const config = typeConfig[paymentType as keyof typeof typeConfig] || { label: paymentType, variant: "outline" as const }
  return <Badge variant={config.variant}>{config.label}</Badge>
}

const formatDate = (date: string | Date | null) => {
  if (!date) return 'N/A'
  const d = typeof date === 'string' ? new Date(date) : date
  return d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  })
}

const formatDateTime = (date: string | Date | null) => {
  if (!date) return 'N/A'
  const d = typeof date === 'string' ? new Date(date) : date
  return d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })
}

const getProviderDisplay = (subscription: Subscription) => {
  if (subscription.stripeCustomerId || subscription.stripeSubscriptionId) {
    return 'Stripe'
  }
  if (subscription.creemCustomerId || subscription.creemSubscriptionId) {
    return 'Creem'
  }
  // Default to WeChat for unknown providers
  return 'WeChat'
}

// Sortable header component
const SortableHeader = ({ column, title, t }: { column: any, title: string, t: any }) => {
  const sortDirection = column.getIsSorted()
  
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          variant="ghost"
          className="h-auto p-0 font-medium hover:bg-transparent hover:text-accent-foreground flex items-center"
        >
          {title}
          <div className="ml-2 flex flex-col">
            {sortDirection === "asc" ? (
              <ArrowUp className="h-3 w-3" />
            ) : sortDirection === "desc" ? (
              <ArrowDown className="h-3 w-3" />
            ) : (
              <ArrowUpDown className="h-3 w-3" />
            )}
          </div>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="start">
        <DropdownMenuItem onClick={() => column.toggleSorting(false)}>
          <ArrowUp className="mr-2 h-4 w-4" />
          {t.admin.subscriptions.table.sort.ascending}
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => column.toggleSorting(true)}>
          <ArrowDown className="mr-2 h-4 w-4" />
          {t.admin.subscriptions.table.sort.descending}
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem onClick={() => column.clearSorting()}>
          <ArrowUpDown className="mr-2 h-4 w-4" />
          {t.admin.subscriptions.table.sort.none}
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

export const useSubscriptionColumns = (): ColumnDef<Subscription>[] => {
  const { t } = useTranslation()

  return [
    {
      accessorKey: "id",
      header: t.admin.subscriptions.table.columns.id,
      cell: ({ row }) => {
        const id = row.getValue("id") as string
        
        const copyToClipboard = async () => {
          try {
            await navigator.clipboard.writeText(id)
            console.log('Subscription ID copied to clipboard:', id)
          } catch (err) {
            console.error('Failed to copy Subscription ID:', err)
          }
        }
        
        return (
          <div className="group relative">
            <div 
              className="font-mono text-sm max-w-[100px] truncate cursor-pointer"
              title={id}
              onClick={copyToClipboard}
            >
              #{id.slice(-8)}
            </div>
            
            {/* Tooltip */}
            <div className="absolute z-50 hidden group-hover:block top-full left-0 pt-1">
              <div className="bg-popover text-popover-foreground shadow-md rounded-md border p-2 text-xs font-mono min-w-max">
                <div className="flex items-center gap-2">
                  <span className="select-all">{id}</span>
                  <button 
                    className="p-1 hover:bg-accent rounded"
                    onClick={copyToClipboard}
                  >
                    <Copy className="h-3 w-3" />
                  </button>
                </div>
                <div className="text-xs text-muted-foreground mt-1">
                  {t.admin.subscriptions.table.actions.clickToCopy}
                </div>
              </div>
            </div>
          </div>
        )
      },
      enableSorting: false,
    },
    {
      accessorKey: "userEmail",
      header: t.admin.subscriptions.table.columns.user,
      cell: ({ row }) => {
        const email = row.getValue("userEmail") as string
        const name = row.original.userName
        return (
          <div className="max-w-[150px]">
            <div className="font-medium truncate text-foreground" title={name || t.common.notAvailable}>
              {name || t.common.notAvailable}
            </div>
            <div className="text-sm text-muted-foreground truncate" title={email || t.common.notAvailable}>
              {email || t.common.notAvailable}
            </div>
          </div>
        )
      },
      enableHiding: false,
    },
    {
      accessorKey: "planId",
      header: t.admin.subscriptions.table.columns.plan,
      cell: ({ row }) => {
        const planId = row.getValue("planId") as string
        return <div className="font-medium">{planId || t.common.notAvailable}</div>
      },
    },
    {
      accessorKey: "status",
      header: t.admin.subscriptions.table.columns.status,
      cell: ({ row }) => getStatusBadge(row.getValue("status"), t),
      enableHiding: false,
    },
    {
      accessorKey: "paymentType",
      header: t.admin.subscriptions.table.columns.paymentType,
      cell: ({ row }) => getPaymentTypeBadge(row.getValue("paymentType"), t),
    },
    {
      id: "provider",
      header: t.admin.subscriptions.table.columns.provider,
      cell: ({ row }) => {
        const provider = getProviderDisplay(row.original)
        return <div className="font-medium">{provider}</div>
      },
      enableHiding: false,
      enableSorting: false,
    },
    {
      accessorKey: "periodStart",
      header: t.admin.subscriptions.table.columns.periodStart,
      cell: ({ row }) => {
        const startDate = row.getValue("periodStart") as string | Date | null
        return <div className="text-sm text-muted-foreground">{formatDate(startDate)}</div>
      },
    },
    {
      accessorKey: "periodEnd",
      header: t.admin.subscriptions.table.columns.periodEnd,
      cell: ({ row }) => {
        const endDate = row.getValue("periodEnd") as string | Date | null
        return <div className="text-sm text-muted-foreground">{formatDate(endDate)}</div>
      },
    },
    {
      accessorKey: "cancelAtPeriodEnd",
      header: t.admin.subscriptions.table.columns.cancelAtPeriodEnd,
      cell: ({ row }) => {
        const willCancel = row.getValue("cancelAtPeriodEnd") as boolean | null
        return (
          <Badge variant={willCancel ? "destructive" : "outline"}>
            {willCancel ? t.common.yes : t.common.no}
          </Badge>
        )
      },
    },
    {
      accessorKey: "createdAt",
      header: ({ column }) => {
        return <SortableHeader column={column} title={t.admin.subscriptions.table.columns.createdAt} t={t} />
      },
      cell: ({ row }) => {
        const date = row.getValue("createdAt") as string | Date | null
        return <div className="text-sm text-muted-foreground">{formatDateTime(date)}</div>
      },
    },
    {
      id: "actions",
      header: () => <div className="text-center">{t.admin.subscriptions.table.columns.actions}</div>,
      cell: ({ row }) => {
        const subscription = row.original

        return (
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" className="h-8 w-8 p-0">
                <span className="sr-only">{t.admin.subscriptions.table.actions.openMenu}</span>
                <MoreHorizontal className="h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>{t.admin.subscriptions.table.actions.actions}</DropdownMenuLabel>
              <DropdownMenuItem 
                onClick={() => {
                  // TODO: Implement view subscription functionality
                  console.log('View subscription:', subscription.id)
                }}
              >
                <ExternalLink className="mr-2 h-4 w-4" />
                {t.admin.subscriptions.table.actions.viewSubscription}
              </DropdownMenuItem>
              <DropdownMenuItem 
                onClick={() => {
                  // TODO: Implement cancel functionality
                  console.log('Cancel subscription:', subscription.id)
                }}
                disabled={subscription.status === 'canceled' || subscription.status === 'cancelled'}
              >
                <RefreshCw className="mr-2 h-4 w-4" />
                {t.admin.subscriptions.table.actions.cancelSubscription}
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        )
      },
      enableHiding: false,
      enableSorting: false,
    },
  ]
}

// 为了向后兼容，保留原来的导出
export const columns: ColumnDef<Subscription>[] = []

// apps/nuxt-app/components/admin/users/columns.tsx
import { h } from 'vue'
import type { ColumnDef } from '@tanstack/vue-table'
import { ArrowUpDown, Copy } from 'lucide-vue-next'
import { useI18n } from 'vue-i18n'
import UsersActionsCell from '@/components/admin/users/UsersActionsCell.vue'

// User type definition based on the API response
export interface User {
  id: string
  name: string | null
  email: string
  role: string // Changed from 'admin' | 'user' to string to match API
  emailVerified: boolean
  banned: boolean | null // Changed to match API (can be null)
  createdAt: string | Date // Can be Date from API
  updatedAt: string | Date // Can be Date from API
}

export const columns: ColumnDef<User>[] = [
  // ID Column (hidden by default, no sorting needed)
  {
    accessorKey: 'id',
    header: () => {
      const { t } = useI18n()
      return <span>{t('admin.users.table.columns.id')}</span>
    },
    cell: ({ row }) => {
      const { t } = useI18n()
      const id = row.getValue('id') as string
      
      // Create tooltip content with copy functionality
      const copyToClipboard = async () => {
        try {
          await navigator.clipboard.writeText(id)
          // You could add a toast notification here
          console.log('ID copied to clipboard:', id)
        } catch (err) {
          console.error('Failed to copy ID:', err)
        }
      }
      
      return (
        <div class="group relative">
          {/* Main ID display */}
          <div 
            class="font-mono text-xs w-[180px] truncate cursor-pointer"
            onClick={copyToClipboard}
          >
            {id}
          </div>
          
          {/* Tooltip that appears on hover */}
          <div class="absolute z-50 hidden group-hover:block top-full left-0 pt-1">
            <div class="bg-popover text-popover-foreground shadow-md rounded-md border p-2 text-xs font-mono min-w-max">
              <div class="flex items-center gap-2">
                <span class="select-all">{id}</span>
                <button
                  class="p-1 hover:bg-accent rounded"
                  onClick={copyToClipboard}
                >
                  <Copy class="h-3 w-3" />
                </button>
              </div>
              <div class="text-xs text-muted-foreground mt-1">Click to copy</div>
            </div>
          </div>
        </div>
      )
    },
    enableSorting: false,
  },
  
  // Name Column (sortable - useful for alphabetical order)
  {
    accessorKey: 'name',
    header: ({ column }) => {
      const { t } = useI18n()
      return (
        <button
          class="flex items-center space-x-2 hover:text-accent-foreground"
          onClick={() => column.toggleSorting(column.getIsSorted() === 'asc')}
        >
          <span>{t('admin.users.table.columns.name')}</span>
          <ArrowUpDown class="ml-2 h-4 w-4" />
        </button>
      )
    },
    cell: ({ row }) => {
      const name = row.getValue('name') as string | null
      return <div class="font-medium">{name || 'N/A'}</div>
    },
  },
  
  // Email Column (sortable - useful for alphabetical order)
  {
    accessorKey: 'email',
    header: ({ column }) => {
      const { t } = useI18n()
      return (
        <button
          class="flex items-center space-x-2 hover:text-accent-foreground"
          onClick={() => column.toggleSorting(column.getIsSorted() === 'asc')}
        >
          <span>{t('admin.users.table.columns.email')}</span>
          <ArrowUpDown class="ml-2 h-4 w-4" />
        </button>
      )
    },
    cell: ({ row }) => {
      const email = row.getValue('email') as string
      return <div class="text-sm">{email}</div>
    },
  },
  
  // Role Column (no sorting needed - just admin/user filter)
  {
    accessorKey: 'role',
    header: () => {
      const { t } = useI18n()
      return <span>{t('admin.users.table.columns.role')}</span>
    },
    cell: ({ row }) => {
      const { t } = useI18n()
      const role = row.getValue('role') as string
      const badgeClass = role === 'admin' 
        ? 'bg-chart-1 text-destructive-foreground'
        : 'bg-primary text-primary-foreground'
      
      // Use translated role names
      const roleLabel = role === 'admin' ? t('dashboard.roles.admin') : t('dashboard.roles.user')
      
      return (
        <span class={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${badgeClass}`}>
          {roleLabel}
        </span>
      )
    },
    enableSorting: false,
  },
  
  // Email Verified Column (no sorting needed - just status display)
  {
    accessorKey: 'emailVerified',
    header: () => {
      const { t } = useI18n()
      return <span>{t('admin.users.table.columns.emailVerified')}</span>
    },
    cell: ({ row }) => {
      const verified = row.getValue('emailVerified') as boolean
      
      if (verified) {
        return (
          <div class="text-foreground">
            ✓ Verified
          </div>
        )
      }
      
      return (
        <div class="text-muted-foreground">
          ✗ Not verified
        </div>
      )
    },
    enableSorting: false,
  },
  
  // Banned Status Column (no sorting needed - just status display)
  {
    accessorKey: 'banned',
    header: () => {
      const { t } = useI18n()
      return <span>Status</span>
    },
    cell: ({ row }) => {
      const banned = row.getValue('banned') as boolean | null
      
      if (banned) {
        return (
          <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-destructive text-destructive-foreground">
            Banned
          </span>
        )
      }
      
      return (
        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-secondary text-secondary-foreground">
          Active
        </span>
      )
    },
    enableSorting: false,
  },
  
  // Created At Column (sortable - very useful for chronological order)
  {
    accessorKey: 'createdAt',
    header: ({ column }) => {
      const { t } = useI18n()
      return (
        <button
          class="flex items-center space-x-2 hover:text-accent-foreground"
          onClick={() => column.toggleSorting(column.getIsSorted() === 'asc')}
        >
          <span>{t('admin.users.table.columns.createdAt')}</span>
          <ArrowUpDown class="ml-2 h-4 w-4" />
        </button>
      )
    },
    cell: ({ row }) => {
      const createdAt = row.getValue('createdAt') as string | Date
      const date = new Date(createdAt)
      const formatted = date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric'
      })
      return <div class="text-sm text-muted-foreground">{formatted}</div>
    },
  },
  
  // Updated At Column (sortable - useful to see recent activity)
  {
    accessorKey: 'updatedAt',
    header: ({ column }) => {
      const { t } = useI18n()
      return (
        <button
          class="flex items-center space-x-2 hover:text-accent-foreground"
          onClick={() => column.toggleSorting(column.getIsSorted() === 'asc')}
        >
          <span>{t('admin.users.table.columns.updatedAt')}</span>
          <ArrowUpDown class="ml-2 h-4 w-4" />
        </button>
      )
    },
    cell: ({ row }) => {
      const updatedAt = row.getValue('updatedAt') as string | Date
      const date = new Date(updatedAt)
      const formatted = date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric'
      })
      return <div class="text-sm text-muted-foreground">{formatted}</div>
    },
  },
  
  // Actions Column (no sorting)
  {
    id: 'actions',
    header: () => {
      const { t } = useI18n()
      return <div class="text-center">{t('admin.users.table.columns.actions')}</div>
    },
    cell: ({ row, table }) => {
      const user = row.original
      
      // Get the onUserUpdated and onUserDeleted functions from table meta
      const meta = table.options.meta as any
      const onUserUpdated = meta?.onUserUpdated
      const onUserDeleted = meta?.onUserDeleted
      
      return h('div', { class: 'flex justify-center' }, 
        h(UsersActionsCell, { 
          user,
          'onUser-updated': onUserUpdated,
          'onUser-deleted': onUserDeleted
        })
      )
    },
    enableSorting: false,
    enableHiding: false,
  },
]
