// apps/next-app/app/[lang]/(auth)/forgot-password/page.tsx
'use client';

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { FormError } from "@/components/ui/form-error";
import { Turnstile } from "@/components/ui/turnstile";
import { Loader2 } from "lucide-react";
import { forgetPasswordSchema } from "@libs/validators/user";
import { authClientReact } from '@libs/auth/authClient';
import type { z } from "zod";
import { useTranslation } from "@/hooks/use-translation";
import { config } from "@config";

type FormData = z.infer<typeof forgetPasswordSchema>;

export default function ForgetPasswordPage() {
  const router = useRouter();
  const { t, locale } = useTranslation();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<{ code?: string; message: string } | null>(null);
  const [emailSent, setEmailSent] = useState(false);
  const [sentEmail, setSentEmail] = useState("");
  const [turnstileToken, setTurnstileToken] = useState<string | null>(null);
  const [turnstileKey, setTurnstileKey] = useState(0); // 用于强制重新渲染 Turnstile

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<FormData>({
    resolver: zodResolver(forgetPasswordSchema),
    defaultValues: {
      email: "",
    },
  });

  const onSubmit = async (data: FormData) => {
    // 如果启用了 captcha 但没有 token，则提示用户
    if (config.captcha.enabled && !turnstileToken) {
      setError({
        code: "CAPTCHA_REQUIRED",
        message: t.auth.forgetPassword.errors.captchaRequired,
      });
      return;
    }

    try {
      setLoading(true);
      setError(null);
      await authClientReact.forgetPassword({
        email: data.email,
        redirectTo: '/reset-password',
        fetchOptions: {
          headers: {
            'X-Locale': locale,
            ...(config.captcha.enabled && turnstileToken ? {
              "x-captcha-response": turnstileToken,
            } : {})
          }
        }
      });
      setEmailSent(true);
      setSentEmail(data.email);
    } catch (err: any) {
      setError({
        code: err.code || "UNKNOWN_ERROR",
        message: err.message || t.common.unexpectedError,
      });
      // 如果验证失败，重置 turnstile token 并强制重新渲染
      if (config.captcha.enabled) {
        setTurnstileToken(null);
        setTurnstileKey(prev => prev + 1); // 强制重新渲染 Turnstile 组件
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card className="w-[380px]">
      {!emailSent ? (
        <>
        <CardHeader className="text-center">
          <CardTitle className="text-xl">{t.auth.forgetPassword.title}</CardTitle>
          <CardDescription>
            {t.auth.forgetPassword.description}
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-6">
          
            <form onSubmit={handleSubmit(onSubmit)}>
              <div className="grid gap-4">
                <div className="grid gap-2">
                  <Label htmlFor="email">{t.auth.forgetPassword.email}</Label>
                  <Input
                    id="email"
                    placeholder={t.auth.forgetPassword.emailPlaceholder}
                    type="email"
                    autoCapitalize="none"
                    autoComplete="email"
                    autoCorrect="off"
                    disabled={loading}
                    {...register("email")}
                  />
                  {errors?.email && (
                    <p className="px-1 text-xs text-red-600">
                      {errors.email.type === 'required'
                        ? t.auth.forgetPassword.errors.requiredEmail
                        : t.auth.forgetPassword.errors.invalidEmail}
                    </p>
                  )}
                </div>

                {/* Cloudflare Turnstile 验证码 */}
                <Turnstile
                  key={turnstileKey}
                  onSuccess={(token: string) => setTurnstileToken(token)}
                  onError={() => setTurnstileToken(null)}
                  onExpire={() => setTurnstileToken(null)}
                />

                <Button disabled={loading || (config.captcha.enabled && !turnstileToken)}>
                  {loading && (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  )}
                  {loading ? t.auth.forgetPassword.submitting : t.auth.forgetPassword.submit}
                </Button>
              </div>
            </form>
          {error && <FormError message={error.message} code={error.code} />}
          <div className="text-muted-foreground *:[a]:hover:text-primary text-center text-xs text-balance *:[a]:underline *:[a]:underline-offset-4">
            {t.auth.forgetPassword.termsNotice} <a href="#">{t.auth.forgetPassword.termsOfService}</a>{" "}
            {t.common.and} <a href="#">{t.auth.forgetPassword.privacyPolicy}</a>.
          </div>
        </CardContent>
        </>
      ) : (
        <div className="text-center space-y-4">
          <h3 className="font-medium">{t.auth.forgetPassword.verification.title}</h3>
          <p className="text-muted-foreground">
            {t.auth.forgetPassword.verification.sent} <span className="font-medium">{sentEmail}</span>
          </p>
          <p className="text-sm text-muted-foreground">
            {t.auth.forgetPassword.verification.checkSpam}
          </p>
        </div>
      )}
    </Card>
  )
}

// apps/nuxt-app/pages/forgot-password.vue
<template>
  <Card class="w-[380px]">
    <!-- Email sent confirmation state -->
    <div v-if="emailSent" class="text-center space-y-4 p-6">
      <h3 class="font-medium">{{ t('auth.forgetPassword.verification.title') }}</h3>
      <p class="text-muted-foreground">
        {{ t('auth.forgetPassword.verification.sent') }} <span class="font-medium">{{ sentEmail }}</span>
      </p>
      <p class="text-sm text-muted-foreground">
        {{ t('auth.forgetPassword.verification.checkSpam') }}
      </p>
    </div>

    <!-- Forgot password form -->
    <div v-else>
      <CardHeader class="text-center">
        <CardTitle class="text-xl">{{ t('auth.forgetPassword.title') }}</CardTitle>
        <CardDescription>
          {{ t('auth.forgetPassword.description') }}
        </CardDescription>
      </CardHeader>
      
      <CardContent class="flex flex-col gap-6">
        <form @submit="onSubmit">
          <div class="grid gap-6">
            <!-- Email input -->
            <div class="grid gap-2">
              <Label for="email">{{ t('auth.forgetPassword.email') }}</Label>
              <div class="relative">
                <Input
                  id="email"
                  v-bind="emailAttrs"
                  v-model="email"
                  type="email"
                  :placeholder="t('auth.forgetPassword.emailPlaceholder')"
                  :class="cn(errors.email && 'border-destructive')"
                  :aria-invalid="errors.email ? 'true' : 'false'"
                  :disabled="loading"
                  autocomplete="email"
                  autocapitalize="none"
                  autocorrect="off"
                />
                <span v-if="errors.email" class="text-destructive text-xs absolute -bottom-5 left-0">
                  {{ errors.email }}
                </span>
              </div>
            </div>

            <!-- Captcha component (if enabled) -->
            <div v-if="captchaEnabled" class="grid gap-2">
              <VueTurnstile
                :key="turnstileKey"
                ref="turnstileRef"
                :site-key="captchaSiteKey"
                v-model="turnstileToken"
                size="flexible"
                @error="onTurnstileError"
                @expired="onTurnstileExpired"
                :theme="isDark ? 'dark' : 'light'"
              />
              <span v-if="turnstileError" class="text-destructive text-xs">
                {{ turnstileError }}
              </span>
            </div>

            <!-- Submit button -->
            <Button 
              type="submit" 
              :disabled="loading || (captchaEnabled && !turnstileToken)"
            >
              <Loader2 v-if="loading" class="mr-2 h-4 w-4 animate-spin" />
              {{ loading ? t('auth.forgetPassword.submitting') : t('auth.forgetPassword.submit') }}
            </Button>
          </div>
        </form>

        <!-- Error display -->
        <FormError v-if="errorMessage" :message="errorMessage" :code="errorCode" />

        <!-- Terms notice -->
        <div class="text-muted-foreground text-center text-xs text-balance">
          {{ t('auth.forgetPassword.termsNotice') }} 
          <a href="#" class="underline underline-offset-4 hover:text-primary">{{ t('auth.forgetPassword.termsOfService') }}</a>
          {{ t('common.and') }} 
          <a href="#" class="underline underline-offset-4 hover:text-primary">{{ t('auth.forgetPassword.privacyPolicy') }}</a>.
        </div>
      </CardContent>
    </div>
  </Card>
</template>

<script setup lang="ts">
import { toTypedSchema } from '@vee-validate/zod'
import { useForm } from 'vee-validate'
import { createValidators } from '@libs/validators'
import { authClientVue } from '@libs/auth/authClient'
import { cn } from '@/lib/utils'
import VueTurnstile from 'vue-turnstile'
import { Loader2 } from 'lucide-vue-next'

// Initialize internationalization and navigation
const { t } = useI18n()
const localePath = useLocalePath()
const { locale } = useI18n()

// Set layout
definePageMeta({
  layout: 'auth'
})

// Set page title and meta tags
useSeoMeta({
  title: t('auth.metadata.forgotPassword.title'),
  description: t('auth.metadata.forgotPassword.description'),
  keywords: t('auth.metadata.forgotPassword.keywords')
})

// State management
const loading = ref(false)
const errorMessage = ref('')
const errorCode = ref('')
const emailSent = ref(false)
const sentEmail = ref('')

// Get runtime configuration
const runtimeConfig = useRuntimeConfig()

// Captcha related state
const captchaEnabled = computed(() => {
  return runtimeConfig.public.captchaEnabled !== 'false'
})

const captchaSiteKey = computed(() => {
  const siteKey = runtimeConfig.public.turnstileSiteKey as string | undefined
  return siteKey || '1x00000000000000000000AA' // Test key
})

const turnstileToken = ref('')
const turnstileError = ref('')
const turnstileRef = ref()
const turnstileKey = ref(0) // Force re-render Turnstile

// Theme detection (simplified version)
const isDark = ref(false)

// Turnstile event handlers
const onTurnstileError = () => {
  turnstileError.value = t('auth.forgetPassword.errors.captchaError')
  turnstileToken.value = ''
}

const onTurnstileExpired = () => {
  turnstileError.value = t('auth.forgetPassword.errors.captchaExpired')
  turnstileToken.value = ''
}

// Create internationalized validators
const { forgetPasswordSchema } = createValidators(t)

// Form validation
const { handleSubmit, errors, defineField, isSubmitting } = useForm({
  validationSchema: toTypedSchema(forgetPasswordSchema),
  initialValues: {
    email: ''
  }
})

// Define form fields
const [email, emailAttrs] = defineField('email', {
  validateOnBlur: true
})

// Handle form submission
const onSubmit = handleSubmit(async (values) => {
  // Validate captcha (if enabled)
  if (captchaEnabled.value && !turnstileToken.value) {
    errorMessage.value = t('auth.forgetPassword.errors.captchaRequired')
    errorCode.value = 'CAPTCHA_REQUIRED'
    return
  }

  loading.value = true
  errorMessage.value = ''
  errorCode.value = ''
  turnstileError.value = ''

  try {
    const fetchOptions: any = {}
    
    // If captcha is enabled, add captcha token to request headers
    if (captchaEnabled.value && turnstileToken.value) {
      fetchOptions.headers = {
        'x-captcha-response': turnstileToken.value,
        'X-Locale': locale.value
      }
    } else {
      fetchOptions.headers = {
        'X-Locale': locale.value
      }
    }

    await authClientVue.forgetPassword({
      email: values.email,
      redirectTo: `/${locale.value}/reset-password`,
      fetchOptions
    })

    emailSent.value = true
    sentEmail.value = values.email
  } catch (err: any) {
    errorMessage.value = err.message || t('common.unexpectedError')
    errorCode.value = err.code || 'UNKNOWN_ERROR'
    
    // If validation fails, reset turnstile token and force re-render
    if (captchaEnabled.value) {
      turnstileToken.value = ''
      turnstileKey.value += 1
    }
  } finally {
    loading.value = false
  }
})
</script>
