// apps/nuxt-app/components/LoginForm.vue
<template>
  <div :class="cn('flex flex-col gap-4', className)">
    <!-- Display error message -->
    <FormError v-if="errorMessage" :message="errorMessage" :code="errorCode" />
    
    <form @submit="onSubmit" class="flex flex-col gap-4">
      <div class="grid gap-6">
        <!-- Email input -->
        <div class="grid gap-2">
          <Label for="email">{{ t('auth.signin.email') }}</Label>
          <div class="relative">
            <Input
              id="email"
              v-bind="emailAttrs"
              v-model="email"
              type="email"
              :placeholder="t('auth.signin.emailPlaceholder')"
              :class="cn(errors.email && 'border-destructive')"
              :aria-invalid="errors.email ? 'true' : 'false'"
              autocomplete="email"
            />
            <span v-if="errors.email" class="text-destructive text-xs absolute -bottom-5 left-0">
              {{ errors.email }}
            </span>
          </div>
        </div>

        <!-- Password input -->
        <div class="grid gap-2">
          <div class="flex items-center">
            <Label for="password">{{ t('auth.signin.password') }}</Label>
            <NuxtLink
              :to="localePath('/forgot-password')"
              class="ml-auto text-sm underline-offset-4 hover:underline"
            >
              {{ t('auth.signin.forgotPassword') }}
            </NuxtLink>
          </div>
          <div class="relative">
            <Input
              id="password"
              v-bind="passwordAttrs"
              v-model="password"
              type="password"
              :class="cn(errors.password && 'border-destructive')"
              :aria-invalid="errors.password ? 'true' : 'false'"
              autocomplete="current-password"
            />
            <span v-if="errors.password" class="text-destructive text-xs absolute -bottom-5 left-0">
              {{ errors.password }}
            </span>
          </div>
        </div>

        <!-- Captcha component (if enabled) -->
        <div v-if="captchaEnabled" class="grid gap-2">
          <VueTurnstile
            ref="turnstileRef"
            :site-key="captchaSiteKey"
            v-model="turnstileToken"
            size="flexible"
            @error="onTurnstileError"
            @expired="onTurnstileExpired"
            :theme="isDark ? 'dark' : 'light'"
          />
          <span v-if="turnstileError" class="text-destructive text-xs">
            {{ turnstileError }}
          </span>
        </div>

        <!-- Remember me option -->
        <div class="flex items-center space-x-2">
          <input
            id="remember"
            v-bind="rememberAttrs"
            v-model="remember"
            type="checkbox"
            class="border-primary text-primary ring-offset-background focus-visible:ring-ring h-4 w-4 rounded border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2"
          />
          <Label for="remember" class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
            {{ t('auth.signin.rememberMe') }}
          </Label>
        </div>

        <!-- Submit button -->
        <Button 
          type="submit" 
          class="w-full" 
          :disabled="loading || isSubmitting || (captchaEnabled && !turnstileToken)"
        >
          {{ loading ? t('auth.signin.submitting') : t('auth.signin.submit') }}
        </Button>
      </div>

      <!-- Registration link -->
      <div class="text-center text-sm">
        {{ t('auth.signin.noAccount') }}
        <NuxtLink :to="localePath('/signup')" class="underline underline-offset-4">
          {{ t('auth.signin.signupLink') }}
        </NuxtLink>
      </div>
    </form>
  </div>
</template>

<script setup lang="ts">
import { toTypedSchema } from '@vee-validate/zod'
import { useForm } from 'vee-validate'
import { createValidators } from '@libs/validators'
import { authClientVue } from '@libs/auth/authClient'
import { cn } from '@/lib/utils'
import VueTurnstile from 'vue-turnstile'

interface Props {
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  className: ''
})

// Initialize internationalization and navigation
const { t } = useI18n()
const localePath = useLocalePath()
const { locale } = useI18n()

// State management
const loading = ref(false)
const errorMessage = ref('')
const errorCode = ref('')

// Get runtime configuration
const runtimeConfig = useRuntimeConfig()

// Captcha related state
const captchaEnabled = computed(() => {
  // Use environment variable or default to true
  return runtimeConfig.public.captchaEnabled !== 'false'
})

const captchaSiteKey = computed(() => {
  // Use Nuxt's public environment variables
  const siteKey = runtimeConfig.public.turnstileSiteKey as string | undefined
  return siteKey || '1x00000000000000000000AA' // Test key
})

const turnstileToken = ref('')
const turnstileError = ref('')
const turnstileRef = ref()

// Theme detection (simplified version)
const isDark = ref(false)

// Turnstile event handlers
const onTurnstileError = () => {
  turnstileError.value = t('auth.signin.captchaError')
  turnstileToken.value = ''
}

const onTurnstileExpired = () => {
  turnstileError.value = t('auth.signin.captchaExpired')
  turnstileToken.value = ''
}

// Create internationalized validators
const { loginFormSchema } = createValidators(t)

// Form validation
const { handleSubmit, errors, defineField, isSubmitting } = useForm({
  validationSchema: toTypedSchema(loginFormSchema),
  initialValues: {
    email: '',
    password: '',
    remember: true
  }
})

// Define form fields
const [email, emailAttrs] = defineField('email', {
  validateOnBlur: true
})
const [password, passwordAttrs] = defineField('password', {
  validateOnBlur: true  
})
const [remember, rememberAttrs] = defineField('remember')

// Handle form submission
const onSubmit = handleSubmit(async (values) => {
  loading.value = true
  errorMessage.value = ''
  errorCode.value = ''
  turnstileError.value = ''

  // Validate captcha (if enabled)
  if (captchaEnabled.value && !turnstileToken.value) {
    turnstileError.value = t('auth.signin.captchaRequired')
    loading.value = false
    return
  }

  try {
    const fetchOptions: any = {}
    
    // If captcha is enabled, add captcha token to request headers
    if (captchaEnabled.value && turnstileToken.value) {
      fetchOptions.headers = {
        'x-captcha-response': turnstileToken.value
      }
    }

    const result = await authClientVue.signIn.email({
      email: values.email,
      password: values.password,
      callbackURL: `/${locale.value}`,
      ...(values.remember ? { rememberMe: true } : {}),
      fetchOptions
    })

    // Check for errors
    if (result && 'error' in result && result.error) {
      const error = result.error
      if (error.code && error.message) {
        errorMessage.value = t('auth.signin.errors.invalidCredentials')
        errorCode.value = error.code
      } else {
        errorMessage.value = t('auth.signin.errors.invalidCredentials')
        errorCode.value = 'UNKNOWN_ERROR'
      }
    } else if (result && 'user' in result) {
      // Login successful, redirect to dashboard
      await navigateTo(localePath('/dashboard'))
    } else {
      // Unknown response format
      errorMessage.value = t('auth.signin.errors.invalidCredentials')
      errorCode.value = 'UNEXPECTED_RESPONSE'
    }
  } catch (err) {
    errorMessage.value = t('auth.signin.errors.invalidCredentials')
    errorCode.value = 'UNEXPECTED_ERROR'
  } finally {
    loading.value = false
  }
})
</script>

// apps/next-app/src/components/login-form.tsx
'use client';

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { authClientReact } from "@libs/auth/authClient";
import { loginFormSchema } from "@libs/validators/user";
import type { z } from "zod";
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { FormError } from "@/components/ui/form-error"

type FormData = z.infer<typeof loginFormSchema>;

export function LoginForm({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [errorCode, setErrorCode] = useState('');

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting }
  } = useForm<FormData>({
    resolver: zodResolver(loginFormSchema),
    defaultValues: {
      email: '',
      password: '',
      remember: true
    },
    mode: 'onBlur', // Enable validation on blur
  });

  const onSubmit = async (data: FormData) => {
    setLoading(true);
    setErrorMessage('');
    setErrorCode('');

    const { error } = await authClientReact.signIn.email(
      {
        email: data.email,
        password: data.password,
        callbackURL: '/',
        ...(data.remember ? { rememberMe: true } : {}),
      }
    );

    if (error) {
      if (error.code && error.message) {
        setErrorMessage(error.message);
        setErrorCode(error.code);
      } else {
        setErrorMessage('An unexpected error occurred');
        setErrorCode('UNKNOWN_ERROR');
      }
    }

    setLoading(false);
  };

  return (
    <div className={cn("flex flex-col gap-4", className)} {...props}>
      <FormError message={errorMessage} code={errorCode} />
      <form onSubmit={handleSubmit(onSubmit)} className="flex flex-col gap-4">
        <div className="grid gap-6">
          <div className="grid gap-2">
            <Label htmlFor="email">Email</Label>
            <div className="relative">
              <Input
                id="email"
                type="email"
                {...register('email')}
                placeholder="m@example.com"
                className={cn(errors.email && "border-destructive")}
                aria-invalid={errors.email ? "true" : "false"}
              />
              {errors.email && (
                <span className="text-destructive text-xs absolute -bottom-5 left-0">
                  {errors.email.message}
                </span>
              )}
            </div>
          </div>
          <div className="grid gap-2">
            <div className="flex items-center">
              <Label htmlFor="password">Password</Label>
              <a
                href="#"
                className="ml-auto text-sm underline-offset-4 hover:underline"
              >
                Forgot your password?
              </a>
            </div>
            <div className="relative">
              <Input
                id="password"
                type="password"
                {...register('password')}
                className={cn(errors.password && "border-destructive")}
                aria-invalid={errors.password ? "true" : "false"}
              />
              {errors.password && (
                <span className="text-destructive text-xs absolute -bottom-5 left-0">
                  {errors.password.message}
                </span>
              )}
            </div>
          </div>
          <div className="flex items-center space-x-2">
            <input
              type="checkbox"
              id="remember"
              {...register('remember')}
              className="border-primary text-primary ring-offset-background focus-visible:ring-ring h-4 w-4 rounded border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2"
            />
            <label htmlFor="remember" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
              Remember me
            </label>
          </div>
          <Button type="submit" className="w-full" disabled={loading || isSubmitting}>
            {loading ? 'Signing in...' : 'Login'}
          </Button>
        </div>
        <div className="text-center text-sm">
          Don&apos;t have an account?{" "}
          <a href="/signup" className="underline underline-offset-4">
            Sign up
          </a>
        </div>
      </form>
    </div>
  );
}
