// apps/next-app/components/ui/country-select.tsx
'use client';

import * as React from "react"
import { cn } from "@/lib/utils"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { countryCodes, type CountryCode } from "@libs/validators/user"

interface CountrySelectProps {
  value?: string
  onValueChange?: (value: string) => void
  placeholder?: string
  disabled?: boolean
  className?: string
}

export function CountrySelect({
  value,
  onValueChange,
  placeholder = "选择国家/地区",
  disabled = false,
  className,
}: CountrySelectProps) {
  const selectedCountry = countryCodes.find((country) => country.code === value)

  return (
    <Select value={value} onValueChange={onValueChange} disabled={disabled}>
      <SelectTrigger className={cn("w-[140px]", className)}>
        <SelectValue placeholder={placeholder}>
          {selectedCountry && (
            <div className="flex items-center gap-2">
              <span className="text-lg">{selectedCountry.flag}</span>
              <span className="text-sm">{selectedCountry.code}</span>
            </div>
          )}
        </SelectValue>
      </SelectTrigger>
      <SelectContent>
        {countryCodes.map((country) => (
          <SelectItem key={country.code} value={country.code}>
            <div className="flex items-center gap-3">
              <span className="text-lg">{country.flag}</span>
              <div className="flex items-center gap-2">
                <span className="font-medium">{country.name}</span>
                <span className="text-sm text-muted-foreground">{country.code}</span>
              </div>
            </div>
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  )
}

// apps/nuxt-app/components/CountrySelect.vue
<template>
  <Select 
    :model-value="modelValue" 
    @update:model-value="handleValueChange"
    :disabled="disabled"
  >
    <SelectTrigger :class="cn('w-[140px]', className)">
      <SelectValue :placeholder="placeholder">
        <div v-if="selectedCountry" class="flex items-center gap-2">
          <span class="text-lg">{{ selectedCountry.flag }}</span>
          <span class="text-sm">{{ selectedCountry.code }}</span>
        </div>
      </SelectValue>
    </SelectTrigger>
    <SelectContent>
      <SelectItem 
        v-for="country in countryCodes" 
        :key="country.code" 
        :value="country.code"
      >
        <div class="flex items-center gap-3">
          <span class="text-lg">{{ country.flag }}</span>
          <div class="flex items-center gap-2">
            <span class="font-medium">{{ country.name }}</span>
            <span class="text-sm text-muted-foreground">{{ country.code }}</span>
          </div>
        </div>
      </SelectItem>
    </SelectContent>
  </Select>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { cn } from '@/lib/utils'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { countryCodes } from '@libs/validators'

interface CountrySelectProps {
  modelValue?: string
  placeholder?: string
  disabled?: boolean
  className?: string
}

// Define props
const props = withDefaults(defineProps<CountrySelectProps>(), {
  placeholder: '选择国家/地区',
  disabled: false,
})

// Define emits
const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

// Handle value changes
const handleValueChange = (value: any) => {
  if (value && typeof value === 'string') {
    emit('update:modelValue', value)
  }
}

// Find selected country based on current value
const selectedCountry = computed(() => 
  countryCodes.find((country) => country.code === props.modelValue)
)
</script>
