// apps/next-app/components/phone-login-form.tsx
'use client';

import { useState, useEffect } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { authClientReact } from '@libs/auth/authClient'
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { FormError } from "@/components/ui/form-error"
import { Turnstile } from "@/components/ui/turnstile"
import { CountrySelect } from "@/components/ui/country-select"
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSlot,
} from "@/components/ui/input-otp"
import { Loader2 } from "lucide-react"
import { createValidators, countryCodes } from "@libs/validators"
import type { z } from "zod"
import { useTranslation } from "@/hooks/use-translation"
import { config } from "@config"

export function PhoneLoginForm({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { t, tWithParams } = useTranslation();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<{ code?: string; message: string } | null>(null);
  const [otpSent, setOtpSent] = useState(false);
  const [otp, setOtp] = useState("");
  const [turnstileToken, setTurnstileToken] = useState<string | null>(null);
  const [turnstileKey, setTurnstileKey] = useState(0); // 用于强制重新渲染 Turnstile
  const [countdown, setCountdown] = useState(0); // 倒计时秒数

  // 创建国际化验证器
  const { phoneLoginSchema, phoneVerifySchema } = createValidators(tWithParams);
  
  type FormData = z.infer<typeof phoneLoginSchema>;
  type VerifyData = z.infer<typeof phoneVerifySchema>;

  const {
    register,
    handleSubmit,
    control,
    watch,
    setValue,
    formState: { errors },
  } = useForm<FormData>({
    resolver: zodResolver(phoneLoginSchema),
    defaultValues: {
      countryCode: '+86', // 默认选择中国
      phone: '',
    },
    mode: 'onBlur', // 添加 onBlur 验证模式
  });

  const countryCode = watch("countryCode");
  const phoneNumber = watch("phone");

  // 倒计时效果
  useEffect(() => {
    let timer: NodeJS.Timeout;
    if (countdown > 0) {
      timer = setTimeout(() => {
        setCountdown(countdown - 1);
      }, 1000);
    }
    return () => {
      if (timer) clearTimeout(timer);
    };
  }, [countdown]);

  // 构建完整的手机号码用于发送短信
  const getFullPhoneNumber = (countryCode: string, phone: string): string => {
    // 统一返回完整的国际格式，让各个SMS提供商自己处理格式
    return countryCode + phone;
  };

  const onSubmitPhone = async (data: FormData) => {
    // 如果启用了 captcha 但没有 token，则提示用户
    if (config.captcha.enabled && !turnstileToken) {
      setError({
        code: "CAPTCHA_REQUIRED",
        message: t.auth.phone.errors.captchaRequired,
      });
      return;
    }

    try {
      setLoading(true);
      setError(null);
      
      const fullPhoneNumber = getFullPhoneNumber(data.countryCode, data.phone);
      console.log('Sending OTP to:', fullPhoneNumber);
      
      const { data: result, error } = await authClientReact.phoneNumber.sendOtp({
        phoneNumber: fullPhoneNumber,
        ...(config.captcha.enabled && turnstileToken ? {
          fetchOptions: {
            headers: {
              "x-captcha-response": turnstileToken,
            },
          }
        } : {})
      });
      
      if (error) {
        console.error('sendOtp error:', error);
        if (error.code) {
          // Use internationalized error messages
          const authErrorMessage = t.auth.authErrors[error.code as keyof typeof t.auth.authErrors] || t.auth.authErrors.UNKNOWN_ERROR;
          setError({
            code: error.code,
            message: authErrorMessage,
          });
        } else {
          setError({
            code: "UNKNOWN_ERROR",
            message: t.auth.authErrors.UNKNOWN_ERROR,
          });
        }
        // 如果验证失败，重置 turnstile token 并强制重新渲染
        if (config.captcha.enabled) {
          setTurnstileToken(null);
          setTurnstileKey(prev => prev + 1); // 强制重新渲染 Turnstile 组件
        }
        return;
      }
      
      console.log('OTP sent successfully');
      setOtpSent(true);
      setCountdown(30); // 启动30秒倒计时
    } catch (err: any) {
      console.error('Send OTP exception:', err);
      setError({
        code: err.code || "SMS_SEND_ERROR",
        message: err.message || t.common.unexpectedError,
      });
      // 如果验证失败，重置 turnstile token 并强制重新渲染
      if (config.captcha.enabled) {
        setTurnstileToken(null);
        setTurnstileKey(prev => prev + 1); // 强制重新渲染 Turnstile 组件
      }
    } finally {
      setLoading(false);
    }
  };

  const onVerifyOTP = async () => {
    if (otp.length !== 6) return;
    
    setLoading(true);
    setError(null);
    
    const fullPhoneNumber = getFullPhoneNumber(countryCode, phoneNumber);
    
    const { data, error } = await authClientReact.phoneNumber.verify({
      phoneNumber: fullPhoneNumber,
      code: otp
    });
    
    if (error) {
      if (error.code) {
        // Use internationalized error messages
        const authErrorMessage = t.auth.authErrors[error.code as keyof typeof t.auth.authErrors] || t.auth.authErrors.UNKNOWN_ERROR;
        setError({
          code: error.code,
          message: authErrorMessage,
        });
      } else {
        setError({
          code: "UNKNOWN_ERROR",
          message: t.auth.authErrors.UNKNOWN_ERROR,
        });
      }
      setLoading(false);
      return;
    }
    
    console.log('isVerified', data);
    if (data) {
      const returnTo = searchParams.get('returnTo');
      router.push(returnTo || `/${locale}`);
    }
    
    setLoading(false);
  };

  // 重新发送验证码
  const onResendOTP = async () => {
    if (countdown > 0 || loading) return;
    
    setLoading(true);
    setError(null);
    
    const fullPhoneNumber = getFullPhoneNumber(countryCode, phoneNumber);
    console.log('Resending OTP to:', fullPhoneNumber);
    
    const { data: result, error } = await authClientReact.phoneNumber.sendOtp({
      phoneNumber: fullPhoneNumber,
      ...(config.captcha.enabled && turnstileToken ? {
        fetchOptions: {
          headers: {
            "x-captcha-response": turnstileToken,
          },
        }
      } : {})
    });
    
    if (error) {
      console.error('Resend OTP error:', error);
      if (error.code) {
        // Use internationalized error messages
        const authErrorMessage = t.auth.authErrors[error.code as keyof typeof t.auth.authErrors] || t.auth.authErrors.UNKNOWN_ERROR;
        setError({
          code: error.code,
          message: authErrorMessage,
        });
      } else {
        setError({
          code: "UNKNOWN_ERROR",
          message: t.auth.authErrors.UNKNOWN_ERROR,
        });
      }
      setLoading(false);
      return;
    }
    
    console.log('OTP resent successfully');
    setCountdown(30); // 重新启动30秒倒计时
    setOtp(""); // 清空之前输入的验证码
    setLoading(false);
  };

  return (
    <div className={cn("flex flex-col gap-4", className)} {...props}>
      {!otpSent ? (
        <form onSubmit={handleSubmit(onSubmitPhone)}>
          <div className="grid gap-4">
            <div className="grid gap-2">
              <Label htmlFor="phone">{t.auth.phone.phoneNumber}</Label>
              <div className="flex gap-2">
                <Controller
                  name="countryCode"
                  control={control}
                  render={({ field }) => (
                    <CountrySelect
                      value={field.value}
                      onValueChange={field.onChange}
                      disabled={loading}
                    />
                  )}
                />
                <Input
                  id="phone"
                  placeholder={t.auth.phone.phoneNumberPlaceholder}
                  type="tel"
                  autoCapitalize="none"
                  autoComplete="tel"
                  autoCorrect="off"
                  disabled={loading}
                  className="flex-1"
                  {...register("phone")}
                />
              </div>
              {errors?.countryCode && (
                <p className="px-1 text-xs text-red-600">
                  {errors.countryCode.message}
                </p>
              )}
              {errors?.phone && (
                <p className="px-1 text-xs text-red-600">
                  {errors.phone.message}
                </p>
              )}
            </div>

            {/* Cloudflare Turnstile 验证码 */}
            <Turnstile
              key={turnstileKey}
              onSuccess={(token: string) => setTurnstileToken(token)}
              onError={() => setTurnstileToken(null)}
              onExpire={() => setTurnstileToken(null)}
            />

            <Button disabled={loading || (config.captcha.enabled && !turnstileToken)}>
              {loading && (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              )}
              {loading ? t.auth.phone.sendingCode : t.actions.sendCode}
            </Button>
          </div>
        </form>
      ) : (
        <form onSubmit={(e) => { e.preventDefault(); onVerifyOTP(); }}>
          <div className="grid gap-6">
            <div className="text-center space-y-2">
              <h3 className="text-lg font-semibold">{t.auth.phone.enterCode}</h3>
              <p className="text-sm text-muted-foreground">
                {t.auth.phone.codeSentTo} {countryCode} {phoneNumber}
              </p>
            </div>

            <div className="space-y-2">
              <div className="flex justify-center">
                <InputOTP
                  maxLength={6}
                  value={otp}
                  onChange={(value) => setOtp(value)}
                  disabled={loading}
                >
                  <InputOTPGroup>
                    <InputOTPSlot index={0} />
                    <InputOTPSlot index={1} />
                    <InputOTPSlot index={2} />
                    <InputOTPSlot index={3} />
                    <InputOTPSlot index={4} />
                    <InputOTPSlot index={5} />
                  </InputOTPGroup>
                </InputOTP>
              </div>
              
              <div className="text-center">
                {countdown > 0 ? (
                  <p className="text-sm text-muted-foreground">
                    {t.auth.phone.resendIn} {countdown} {t.auth.phone.seconds}
                  </p>
                ) : (
                  <Button
                    type="button"
                    variant="link"
                    className="text-sm"
                    onClick={onResendOTP}
                    disabled={loading}
                  >
                    {t.auth.phone.resendCode}
                  </Button>
                )}
              </div>
            </div>

            <div className="flex gap-3">
              <Button 
                type="button"
                variant="outline"
                className="flex-1"
                onClick={() => {
                  setOtpSent(false);
                  setOtp("");
                  setCountdown(0);
                  setError(null);
                }}
                disabled={loading}
              >
                {t.actions.back}
              </Button>
              <Button 
                type="submit"
                className="flex-1"
                disabled={loading || otp.length !== 6}
              >
                {loading && (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                )}
                {loading ? t.auth.phone.verifying : t.actions.verify}
              </Button>
            </div>
          </div>
        </form>
      )}
      {error && <FormError message={error.message} code={error.code} />}
    </div>
  );
}

// apps/nuxt-app/components/PhoneLoginForm.vue
<template>
  <div :class="cn('flex flex-col gap-4', className)">
    <!-- Phone number input form -->
    <form v-if="!otpSent" @submit="onSubmitPhone" class="grid gap-4">
      <div class="grid gap-2">
        <Label for="phone">{{ t('auth.phone.phoneNumber') }}</Label>
        <div class="flex gap-2">
          <!-- Country code selector -->
          <CountrySelect
            v-model="countryCode"
            :disabled="loading"
          />
          <!-- Phone number input -->
          <Input
            id="phone"
            v-bind="phoneAttrs"
            v-model="phone"
            type="tel"
            :placeholder="t('auth.phone.phoneNumberPlaceholder')"
            autocapitalize="none"
            autocomplete="tel"
            autocorrect="off"
            :disabled="loading"
            class="flex-1"
            :class="cn(errors.phone && 'border-destructive')"
          />
        </div>
        <!-- Validation errors -->
        <span v-if="errors.countryCode" class="px-1 text-xs text-red-600">
          {{ errors.countryCode }}
        </span>
        <span v-if="errors.phone" class="px-1 text-xs text-red-600">
          {{ errors.phone }}
        </span>
      </div>

      <!-- Captcha component (if enabled) -->
      <div v-if="captchaEnabled" class="grid gap-2">
        <VueTurnstile
          ref="turnstileRef"
          :site-key="captchaSiteKey"
          v-model="turnstileToken"
          size="flexible"
          @error="onTurnstileError"
          @expired="onTurnstileExpired"
          :theme="isDark ? 'dark' : 'light'"
        />
        <span v-if="turnstileError" class="text-destructive text-xs">
          {{ turnstileError }}
        </span>
      </div>

      <!-- Submit button -->
      <Button 
        type="submit" 
        :disabled="loading || (captchaEnabled && !turnstileToken)"
      >
        <Loader2 v-if="loading" class="mr-2 h-4 w-4 animate-spin" />
        {{ loading ? t('auth.phone.sendingCode') : t('actions.sendCode') }}
      </Button>
    </form>

    <!-- OTP verification form -->
    <form v-else @submit.prevent="onVerifyOTP" class="grid gap-6">
      <div class="text-center space-y-2">
        <h3 class="text-lg font-semibold">{{ t('auth.phone.enterCode') }}</h3>
        <p class="text-sm text-muted-foreground">
          {{ t('auth.phone.codeSentTo') }} {{ countryCode }} {{ phone }}
        </p>
      </div>

      <div class="space-y-2">
        <!-- OTP Input using PinInput component -->
        <div class="flex justify-center">
          <PinInput
            v-model="otpArray"
            :length="6"
            :disabled="loading"
            class="gap-2"
          >
          <PinInputGroup>
        <PinInputSlot
          v-for="(id, index) in 6"
          :key="id"
          :index="index"
        />
      </PinInputGroup>

          </PinInput>
        </div>
        
        <div class="text-center">
          <p v-if="countdown > 0" class="text-sm text-muted-foreground">
            {{ t('auth.phone.resendIn') }} {{ countdown }} {{ t('auth.phone.seconds') }}
          </p>
          <Button
            v-else
            type="button"
            variant="link"
            class="text-sm"
            @click="onResendOTP"
            :disabled="loading"
          >
            {{ t('auth.phone.resendCode') }}
          </Button>
        </div>
      </div>

      <div class="flex gap-3">
        <Button 
          type="button"
          variant="outline"
          class="flex-1"
          @click="goBack"
          :disabled="loading"
        >
          {{ t('actions.back') }}
        </Button>
        <Button 
          type="submit"
          class="flex-1"
          :disabled="loading || otpString.length !== 6"
        >
          <Loader2 v-if="loading" class="mr-2 h-4 w-4 animate-spin" />
          {{ loading ? t('auth.phone.verifying') : t('actions.verify') }}
        </Button>
      </div>
    </form>

    <!-- Error display -->
    <FormError v-if="error" :message="error.message" :code="error.code" />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { toTypedSchema } from '@vee-validate/zod'
import { useForm } from 'vee-validate'
import { createValidators } from '@libs/validators'
import { authClientVue } from '@libs/auth/authClient'
import { cn } from '@/lib/utils'
import VueTurnstile from 'vue-turnstile'
import { Loader2 } from 'lucide-vue-next'
import { PinInput, PinInputSlot } from '@/components/ui/pin-input'

interface Props {
  className?: string
}

const props = withDefaults(defineProps<Props>(), {
  className: ''
})

// Initialize internationalization and navigation
const { t } = useI18n()
const router = useRouter()
const localePath = useLocalePath()
const { locale } = useI18n()

// State management
const loading = ref(false)
const error = ref<{ code?: string; message: string } | null>(null)
const otpSent = ref(false)
const otp = ref('')
const otpArray = ref<string[]>([])
const turnstileToken = ref('')
const turnstileError = ref('')
const turnstileRef = ref()
const countdown = ref(0)

// Get runtime configuration
const runtimeConfig = useRuntimeConfig()

// Captcha related state
const captchaEnabled = computed(() => {
  // Use environment variable or default to true
  return runtimeConfig.public.captchaEnabled !== 'false'
})

const captchaSiteKey = computed(() => {
  // Use Nuxt's public environment variables
  const siteKey = runtimeConfig.public.turnstileSiteKey as string | undefined
  return siteKey || '1x00000000000000000000AA' // Test key
})

// Theme detection (simplified version)
const isDark = ref(false)

// Computed OTP string from array
const otpString = computed(() => otpArray.value.join(''))

// Watch otpArray changes to update otp ref
watch(otpArray, (newValue) => {
  otp.value = newValue.join('')
}, { deep: true })

// Turnstile event handlers
const onTurnstileError = () => {
  turnstileError.value = t('auth.signin.captchaError')
  turnstileToken.value = ''
}

const onTurnstileExpired = () => {
  turnstileError.value = t('auth.signin.captchaExpired')
  turnstileToken.value = ''
}

// Create internationalized validators
const { phoneLoginSchema } = createValidators(t)

// Form validation
const { handleSubmit, errors, defineField } = useForm({
  validationSchema: toTypedSchema(phoneLoginSchema),
  validateOnMount: false,
  initialValues: {
    countryCode: '+86', // Default to China
    phone: ''
  }
})

// Define form fields
const [countryCode] = defineField('countryCode', {
  validateOnBlur: true,
  validateOnModelUpdate: false
})
const [phone, phoneAttrs] = defineField('phone', {
  validateOnBlur: true,
  validateOnModelUpdate: false
})

// Countdown effect
watch(countdown, (newValue) => {
  if (newValue > 0) {
    setTimeout(() => {
      countdown.value = newValue - 1
    }, 1000)
  }
})

// Build complete phone number for SMS
const getFullPhoneNumber = (countryCode: string, phone: string): string => {
  return countryCode + phone
}

// Handle phone form submission
const onSubmitPhone = handleSubmit(async (values) => {
  // If captcha is enabled but no token, prompt user
  if (captchaEnabled.value && !turnstileToken.value) {
    error.value = {
      code: "CAPTCHA_REQUIRED",
      message: t('auth.phone.errors.captchaRequired'),
    }
    return
  }

  try {
    loading.value = true
    error.value = null
    
    const fullPhoneNumber = getFullPhoneNumber(values.countryCode, values.phone)
    console.log('Sending OTP to:', fullPhoneNumber)
    
    const { data: result, error: authError } = await authClientVue.phoneNumber.sendOtp({
      phoneNumber: fullPhoneNumber,
      ...(captchaEnabled.value && turnstileToken.value ? {
        fetchOptions: {
          headers: {
            "x-captcha-response": turnstileToken.value,
          },
        }
      } : {})
    })
    
    if (authError) {
      console.error('sendOtp error:', authError)
      error.value = {
        code: "SMS_SEND_ERROR",
        message: authError.message || t('common.unexpectedError'),
      }
      // Reset turnstile token if verification failed
      if (captchaEnabled.value) {
        turnstileToken.value = ''
        // Force re-render Turnstile component
        if (turnstileRef.value) {
          turnstileRef.value.reset()
        }
      }
      return
    }
    
    console.log('OTP sent successfully')
    otpSent.value = true
    countdown.value = 30 // Start 30-second countdown
  } catch (err: any) {
    console.error('Send OTP exception:', err)
    error.value = {
      code: err.code || "SMS_SEND_ERROR",
      message: err.message || t('common.unexpectedError'),
    }
    // Reset turnstile token if verification failed
    if (captchaEnabled.value) {
      turnstileToken.value = ''
      if (turnstileRef.value) {
        turnstileRef.value.reset()
      }
    }
  } finally {
    loading.value = false
  }
})

// Handle OTP verification
const onVerifyOTP = async () => {
  if (otpString.value.length !== 6) return
  
  try {
    loading.value = true
    error.value = null
    
    const fullPhoneNumber = getFullPhoneNumber(countryCode.value || '+86', phone.value || '')
    
    const isVerified = await authClientVue.phoneNumber.verify({
      phoneNumber: fullPhoneNumber,
      code: otpString.value
    })
    
    console.log('isVerified', isVerified)
    if (isVerified) {
      await navigateTo(localePath('/'))
    }
  } catch (err: any) {
    error.value = {
      code: err.code || "UNKNOWN_ERROR",
      message: err.message || t('common.unexpectedError'),
    }
  } finally {
    loading.value = false
  }
}

// Resend OTP
const onResendOTP = async () => {
  if (countdown.value > 0 || loading.value) return
  
  try {
    loading.value = true
    error.value = null
    
    const fullPhoneNumber = getFullPhoneNumber(countryCode.value || '+86', phone.value || '')
    console.log('Resending OTP to:', fullPhoneNumber)
    
    const { data: result, error: authError } = await authClientVue.phoneNumber.sendOtp({
      phoneNumber: fullPhoneNumber,
      ...(captchaEnabled.value && turnstileToken.value ? {
        fetchOptions: {
          headers: {
            "x-captcha-response": turnstileToken.value,
          },
        }
      } : {})
    })
    
    if (authError) {
      console.error('Resend OTP error:', authError)
      error.value = {
        code: "SMS_SEND_ERROR",
        message: authError.message || t('common.unexpectedError'),
      }
      return
    }
    
    console.log('OTP resent successfully')
    countdown.value = 30 // Restart 30-second countdown
    otpArray.value = [] // Clear previous OTP input
  } catch (err: any) {
    console.error('Resend OTP exception:', err)
    error.value = {
      code: err.code || "SMS_SEND_ERROR",
      message: err.message || t('common.unexpectedError'),
    }
  } finally {
    loading.value = false
  }
}

// Go back to phone input
const goBack = () => {
  otpSent.value = false
  otpArray.value = []
  countdown.value = 0
  error.value = null
}
</script>
