// apps/next-app/components/social-auth.tsx
'use client';

import { SocialButton, type SocialProvider } from "@/components/ui/social-button";
import { cn } from "@/lib/utils";
import { authClientReact } from '@libs/auth/authClient';
import { useRouter } from 'next/navigation';
import { useTranslation } from '@/hooks/use-translation';

interface SocialAuthProps extends React.HTMLAttributes<HTMLDivElement> {
  providers?: SocialProvider[];
}

const defaultProviders: SocialProvider[] = ['google', 'github', 'wechat', 'phone'];

export function SocialAuth({
  className,
  providers = defaultProviders,
  ...props
}: SocialAuthProps) {
  const router = useRouter();
  const { locale: currentLocale } = useTranslation();

  const handleProviderClick = async (provider: SocialProvider) => {
    switch (provider) {
      case 'wechat':
        router.push(`/${currentLocale}/wechat`);
        break;
      case 'phone':
        router.push(`/${currentLocale}/cellphone`);
        break;
      default:
        // Use default social login flow for other providers
        authClientReact.signIn.social({
          provider,
        });
    }
  };

  return (
    <div className={cn("flex flex-col gap-4", className)} {...props}>
      {providers.map((provider) => (
        <SocialButton 
          key={provider} 
          provider={provider} 
          onClick={() => handleProviderClick(provider)}
        />
      ))}
    </div>
  );
}

// apps/nuxt-app/components/SocialAuth.vue
<template>
  <div :class="cn('flex flex-col gap-4', className)">
    <SocialButton 
      v-for="provider in providers" 
      :key="provider" 
      :provider="provider" 
      @click="handleProviderClick(provider)"
    />
  </div>
</template>

<script setup lang="ts">
import { cn } from '@/lib/utils'
import { authClientVue } from '@libs/auth/authClient'
import type { SocialProvider } from '@/types/auth'

interface Props {
  className?: string
  providers?: SocialProvider[]
}

const props = withDefaults(defineProps<Props>(), {
  className: '',
  providers: () => ['google', 'github', 'wechat', 'phone']
})

// Navigation
const localePath = useLocalePath()

// Handle provider click
const handleProviderClick = async (provider: SocialProvider) => {
  switch (provider) {
    case 'wechat':
      await navigateTo(localePath('/wechat'))
      break
    case 'phone':
      await navigateTo(localePath('/cellphone'))
      break
    default:
      // Other providers use default social login flow
      await authClientVue.signIn.social({
        provider,
      })
  }
}
</script>
